### ISSUE TITLE
Front | add LoadingPage

### ISSUE THREAD

**Issue by nyaneet** [a-givertzman/sss-computing-client#29]
- [x] #30;
- [x] #12;
- [x] Add system with sections so that you can choose type of configured cargo (e.g., ballast, store);
- [x] Add ballast and store tanks configurator #46;
- [x] Add other stores configurator #47;
- [x] Add hold configurator #52;
- [x] Add container configurator #59;
- [ ] #72
